# this is a workflow to check the formatting of the code to make sure that the
# commits adhere to the black styling. Code was pulled from following source:
# https://black.readthedocs.io/en/stable/integrations/github_actions.html

name: Lint-Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./manhattan"
          version: "21.5b1"
