# this is a workflow to run mypy on any code pushed to the repo to perform
# static type checking. Code was adapted from the following sources:
# https://doedotdev.medium.com/mypy-for-github-action-7da1ebee99e7
# https://autobencoder.com/2020-08-24-conda-actions/

name: mypy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file env.yml --name base
    - name: mypy on source code
      run: |
        $CONDA/bin/mypy manhattan/
